In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import plotly.express as px
import plotly.graph_objects as go

## Dataset Creation

In [ ]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50, random_state=13)

In [ ]:
df = pd.DataFrame({'feature_1':X[:,0], 'feature_2':X[:,1], 'target':y})

In [ ]:
df.shape

(100, 3)

In [ ]:
df.head()

,feature_1,feature_2,target
0,1.892742,0.490872,216.617730
1,0.514329,0.217452,76.023958
2,-0.389656,0.291641,-63.806961
3,0.817306,0.154205,172.989994
4,0.501137,1.749242,56.024963


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   feature_1  100 non-null    float64
 1   feature_2  100 non-null    float64
 2   target     100 non-null    float64
dtypes: float64(3)
memory usage: 2.5 KB


In [ ]:
df.describe()

,feature_1,feature_2,target
count,100.000000,100.000000,100.000000
mean,-0.021864,-0.065244,-5.283559
std,0.875106,0.890243,94.925151
min,-2.319848,-2.206867,-209.742777
25%,-0.652672,-0.714543,-66.463876
50%,-0.180904,-0.035074,-12.832299
75%,0.562860,0.493446,50.578568
max,2.386746,1.849613,270.663681


## 3D Plotting

In [ ]:
px.scatter_3d(df, x = 'feature_1', y = 'feature_2', z = 'target')

## Non - Closed Form Solution
Using Sklearn

## Spliting Features

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Modeling

In [ ]:
mlr = LinearRegression()

In [ ]:
mlr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = mlr.predict(X_test)

## Regression Metrics

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mae

37.32504872232687

In [ ]:
mse = mean_squared_error(y_test, y_pred)
mse

2050.9364971961086

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

0.7425986028374062

## Closed Form Solution
OLS Meathod - using formula

In [ ]:
from sklearn.datasets import load_diabetes

In [ ]:
X, y = load_diabetes(return_X_y=True)

In [ ]:
print(X)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990749
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06833155
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286131
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04688253
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452873
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00422151
   0.00306441]]


In [ ]:
print(y)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.  83. 128. 102. 302. 198.  95.  53. 134. 144. 232.  81. 104.  59.
 246. 297. 258. 229. 275. 281. 179. 200. 200. 173. 180.  84. 121. 161.
  99. 109. 115. 268. 274. 158. 107.  83. 103. 272.  85. 280. 336. 281.
 118. 317. 235.  60. 174. 259. 178. 128.  96. 126. 288.  88. 292.  71.
 197. 186.  25.  84.  96. 195.  53. 217. 172. 131. 214.  59.  70. 220.
 268. 152.  47.  74. 295. 101. 151. 127. 237. 225.  81. 151. 107.  64.
 138. 185. 265. 101. 137. 143. 141.  79. 292. 178.  91. 116.  86. 122.
  72. 

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
class MLR():
  def __init__(self):
        self.coef_ = None
        self.intercept_ = None

  def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)

        #calculate betas
        betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

  def predict(self, X_test):
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        return y_pred

In [ ]:
mlr = MLR()

In [ ]:
mlr.fit(X_train, y_train)

In [ ]:
y_pred = mlr.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

0.43993386615689634

In [ ]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [ ]:
mlr.intercept_

np.float64(151.88331005254165)

## Gradient Decent - Batching GD
Finds Coef for entire data at once


In [ ]:
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50, random_state=13)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
class BGD:

  def __init__(self, lr = 0.01, epochs = 100):
    self.lr = lr
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None

  def fit(self, X, y):
    self.intercept_ = 0
    self.coef_ = np.ones(X.shape[1])

    for i in range(self.epochs):
      # intercept
      #Vectorization - Makinng changes wrt to *Error*
      y_hat = np.dot(X, self.coef_) + self.intercept_
      intercept_der = -2 * np.mean(y-y_hat)
      self.intercept_ = self.intercept_ - (self.lr * intercept_der)

      # coeff
      coef_der = -2 * np.dot((y-y_hat), X)
      self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_)
    print(self.coef_)

  def predict(self, X):
    return np.dot(X, self.coef_) + self.intercept_   # y_pred = mx + b

In [ ]:
bgd = BGD()

In [ ]:
bgd.fit(X_train, y_train)

1.2759229889304593
[85.16618015 34.47454524]


In [ ]:
y_pred = bgd.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

0.7435443556467407

In [ ]:
bgd.coef_

array([85.16618015, 34.47454524])

In [ ]:
bgd.intercept_

np.float64(1.2759229889304593)

## Gradient Decent - Stocastic
Finds coef and for every row

In [ ]:
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_diabetes(return_X_y=True)

In [ ]:
scalar = StandardScaler()
X = scalar.fit_transform(X)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
class SGD:

  def __init__(self, lr = 0.01, epochs = 100):
    self.lr = lr
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None

  def fit(self, X, y):
    self.intercept_ = 0
    self.coef_ = np.ones(X.shape[1])

    for i in range(self.epochs):
      idx = np.random.randint(0, X.shape[0]) # Moved inside the loop
      # intercept
      #Vectorization - Makinng changes wrt to *Error*
      y_hat = np.dot(X[idx], self.coef_) + self.intercept_
      intercept_der = -2 *(y[idx]-y_hat)
      self.intercept_ = self.intercept_ - (self.lr * intercept_der)

      # coeff
      coef_der = -2 * (y[idx]-y_hat) * X[idx] # Corrected to use X[idx]
      self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_)
    print(self.coef_)

  def predict(self, X):
    return np.dot(X, self.coef_) + self.intercept_   # y_pred = mx + b

In [ ]:
sgd = SGD()

In [ ]:
sgd.fit(X_train, y_train)

134.68525056519226
[  1.29020159 -23.12349815   1.20810083  11.60753151   0.93329397
  -4.81096006  -5.70269251   3.14297639  29.03758737   9.34977156]


In [ ]:
y_pred = sgd.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

0.24082508040518735

In [ ]:
sgd.coef_

array([  1.29020159, -23.12349815,   1.20810083,  11.60753151,
         0.93329397,  -4.81096006,  -5.70269251,   3.14297639,
        29.03758737,   9.34977156])

In [ ]:
sgd.intercept_

np.float64(134.68525056519226)

##Gradient Descent - Mini Batch GD
Finds coef according to batch size i.e he batch/entire data is divided into mini batches according to user input

In [ ]:
import random
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_diabetes(return_X_y=True)

In [ ]:
scalar = StandardScaler()
X = scalar.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [ ]:
class MBGD:

  def __init__(self,batch_size = 10, lr = 0.01, epochs = 100):
    self.lr = lr
    self.epochs = epochs
    self.coef_ = None
    self.intercept_ = None
    self.batch_size = batch_size

  def fit(self, X, y):
    self.intercept_ = 0.0 # Initialize as float
    self.coef_ = np.ones(X.shape[1])

    for i in range(self.epochs):
      for j in range(int(X.shape[0]/self.batch_size)):
        # Generate batch indices
        idx = random.sample(range(X.shape[0]), self.batch_size)

        X_batch = X[idx]
        y_batch = y[idx]

        # intercept
        y_hat = np.dot(X_batch, self.coef_) + self.intercept_
        intercept_der = -2 * np.mean(y_batch-y_hat) # Average over batch
        self.intercept_ = self.intercept_ - (self.lr * intercept_der)

        # coeff
        coef_der = -2 * np.dot((y_batch-y_hat), X_batch) # Use dot product for coefficients
        self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_)
    print(self.coef_)

  def predict(self, X):
    return np.dot(X, self.coef_) + self.intercept_   # y_pred = mx + b

In [ ]:
mbgd = MBGD()

In [ ]:
mbgd.fit(X_train, y_train)

154.06530862622796
[ 14.7419736   -6.15748157  19.74224366  18.15513815 -37.10817357
  24.46639743   2.98740702   0.2312837   39.78928935   1.5196805 ]


In [ ]:
y_pred = mbgd.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

0.35880385262981873

In [ ]:
mbgd.coef_

array([ 14.7419736 ,  -6.15748157,  19.74224366,  18.15513815,
       -37.10817357,  24.46639743,   2.98740702,   0.2312837 ,
        39.78928935,   1.5196805 ])

In [ ]:
mbgd.intercept_

np.float64(154.06530862622796)