##Question 1: Linear Regression (Predictive Regression)
Task: Build aLinear Re gression model to forecast employee salaries.
Details: Treat Salary_USD as your continuous target (y) variable. Use Age, Experience_Yrs, Education_Yrs, and Remote_Worker as feature inputs (X).


In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score

In [56]:
data = pd.read_excel('/content/employee_ml_practice_data.xlsx')
df = pd.DataFrame(data)
df.sample(10)

,StudentID,Age,Experience_Yrs,Education_Yrs,Remote_Worker,Salary_USD,Left_Company
6,7,60,12,16,0,108600,0
29,30,49,10,21,1,104600,1
9,10,32,8,16,1,91000,0
49,50,56,11,21,1,105900,0
43,44,47,8,16,1,90100,0
57,58,63,12,16,0,104700,0
86,87,41,9,16,1,93600,0
46,47,49,9,16,1,92900,0
4,5,29,5,16,1,74000,0
41,42,35,7,16,0,92600,0


In [26]:
X = df.iloc[:,1:5]
y = df.iloc[:,5]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [29]:
lr.predict(X_test)

array([ 78669.55626392, 103438.8046698 ,  68976.52194933,  85586.58037093,
        75980.61146739,  72341.1792466 ,  82354.05565826,  81535.20789472,
        78383.77866218,  99650.8292588 ,  97242.56023707,  96381.78331569,
       102090.02476016, 111906.45889284,  80842.21668438,  79177.10787348,
        82381.8441222 ,  92315.89496545,  98831.98149526,  89377.69379763])

##Question 2: Logistic Regression (Binary Classification)
Task: Implement a Logistic Regression model to discover retention risks.
Details: Isolate Left_Company (0 = Stayed, 1 = Left) as your binary target label. Use all remaining variables except StudentID as your features.

In [30]:
X = df.iloc[:,1:6]
y = df.iloc[:,-1]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [32]:
sc = StandardScaler()
X_train_scaler = sc.fit_transform(X_train)
X_test_scaler = sc.transform(X_test)

In [33]:
log = LogisticRegression()
log.fit(X_train_scaler, y_train)

LogisticRegression()

In [34]:
log.predict(X_test_scaler)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Question 3: Decision Tree Classifier & Regressor (Dual Application)
Task: Train two separate Decision Tree models to map out internal trends.
Tree A (Regressor): Predict Salary_USD. Keep tree complexity manageable by setting max_depth=3.
Tree B (Classifier): Predict whether an employee will churn (Left_Company).

Decision Tree Classifier

In [89]:
X = df.iloc[:,1:6]
y = df.iloc[:,-1]

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [91]:
clf = DecisionTreeClassifier(criterion= 'entropy', max_depth=3, class_weight='balanced',random_state=42)
clf.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=3, random_state=42)

In [92]:
clf.predict(X_test)

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

Decision Tree Regressor

In [93]:
X = df.iloc[:,1:5]
y = df.iloc[:,5]

In [94]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [95]:
reg = DecisionTreeRegressor(min_samples_split=3,max_depth=3, max_leaf_nodes=8,random_state=42)
reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=3, max_leaf_nodes=8, min_samples_split=3,
                      random_state=42)

In [96]:
reg.predict(X_test)

array([ 79466.66666667, 102990.47619048,  66350.        ,  91600.        ,
        77000.        ,  77806.25      ,  79466.66666667,  79466.66666667,
        79466.66666667, 102990.47619048,  91600.        ,  91600.        ,
       102990.47619048, 102990.47619048,  79466.66666667,  77806.25      ,
        77806.25      ,  91600.        , 102990.47619048,  91600.        ])

##Question 4: Random Forest (Ensemble Learning)
Task: Build a Random Forest Classifier to maximize predictive accuracy for employee turnover (Left_Company).
Details: Initialize an ensemble of 50 trees (n_estimators=50) to evaluate the dataset.

In [43]:
X = df.iloc[:,1:6]
y = df.iloc[:,-1]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [45]:
rf = RandomForestClassifier(n_estimators=50, random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50, random_state=42)

In [46]:
y_pred = rf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8
